"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "@/redux/provider";
import { store } from "@/redux/store";
import { loadUser } from "@/redux/reducers/auth-reducer";
import AlertHandler from "./components/alert";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

store.dispatch(loadUser());

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-screen-2xl mx-auto min-h-screen">
        <AlertHandler/>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
