"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "@/redux/provider";
import { store } from "@/redux/store";
import { loadUser } from "@/redux/reducers/auth-reducer";
import { useEffect } from "react";

export const metadata: Metadata = {
  // title: 'Create Next App',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    store.dispatch(loadUser());
  }, []);
  return (
    <html lang="en">
      <body className="max-w-screen-2xl mx-auto flex flex-col min-h-screen">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
